---
count: 8
default:
  restart: 0
  wait: 1
name: git-workflow-tools
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - test
  2:
    edit: base
  3:
    edit: utils
editor:
  helper: |
    sub {
        my ($self, $group) = @_;
        return () if $group !~ /^cmd-/;

        my ($cmd) = $group =~ /cmd-(.*)/;
        my $lib = join '', map {ucfirst $_} split /-/, $cmd;
        return (
            "bin/git-$cmd",
            "lib/App/Git/Workflow/Command/$lib.pm",
            "t/$group.t",
        );
    }
  helper_autocomplete: |
    sub {
      my ($pos, $args) = @_;
      my $arg = $args->[$pos] || '';
      my $argument = $arg && $arg ne 'edit' ? qr/^$arg/ : qr/./;

      my @list = map {/^t\/(cmd-.*).t$/; $1} glob "t/cmd-*.t";

      return @list;
    }
  files:
    base:
      - lib/App/Git/Workflow.pm
      - lib/App/Git/Workflow/Command.pm
      - lib/App/Git/Workflow/Repository.pm
    utils:
      - lib/App/Git/Workflow/Pom.pm
      - lib/Mock/App/Git/Workflow/Repository.pm
      - lib/Test/Git/Workflow/Command.pm
    pom:
      - bin/git-pom
      - lib/App/Git/Workflow/Command/Pom.pm
      - t/cmd-pom.t
      - lib/App/Git/Workflow/Pom.pm
      - t/pom.t
