#!/usr/bin/perl

# Created on: 2014-12-14 07:20:23
# Create by:  Ivan Wills
# $Id$
# $Revision$, $HeadURL$, $Date$
# $Revision$, $Source$, $Date$

use strict;
use warnings;
use Getopt::Long;
use Pod::Usage;
use Data::Dumper qw/Dumper/;
use English qw/ -no_match_vars /;
use FindBin qw/$Bin/;
use Path::Tiny;
use File::chdir;

our $VERSION = 1.1.20;
my ($name)   = $PROGRAM_NAME =~ m{^.*/(.*?)$}mxs;

my %option = (
    sleep   => 10,
    verbose => 0,
    man     => 0,
    help    => 0,
    VERSION => 0,
);

main();
exit 0;

sub main {

    Getopt::Long::Configure('bundling');
    GetOptions(
        \%option,
        'force|f',
        'verbose|v+',
        'man',
        'help',
        'VERSION!',
    ) or pod2usage(2);

    if ( $option{'VERSION'} ) {
        print "$name Version = $VERSION\n";
        exit 1;
    }
    elsif ( $option{'man'} ) {
        pod2usage( -verbose => 2 );
    }
    elsif ( $option{'help'} ) {
        pod2usage( -verbose => 1 );
    }


    my $base_dir = path($0)->parent;
    create($base_dir) if $option{force} || !-d $base_dir->child('git-01-master');

    run($base_dir);

    return;
}

sub run {
    my ($base_dir) = @_;

    local $CWD = $base_dir->child('git-02-parent');
    my $file = path('file');
    my $odd = path('odd');

    while (1) {
        if (time % 2) {
            $odd->append(rand 100, "\n");
        }
        $file->append(rand 100000, "\n");

        system qw/git add ./;
        system qw/git commit -m/, time . ' Added changes';
        system qw/git pull --ff -r/;
        system qw/git push/;

        sleep $option{sleep};
        print "\n";
    }

    return;
}

sub create {
    my ($base_dir) = @_;

    local $CWD = $base_dir;

    # Create "master" repository
    my $dir_master = path('git-01-master');
    $dir_master->remove_tree({ safe => 0 });
    $dir_master->mkpath;
    $dir_master->child('first-file')->spew("The first file\n");

    {
        local $CWD = $dir_master;
        system qw/git init/;
        system qw/git add ./;
        system qw/git commit -m /, 'Initial commit';
        system qw/git checkout -b out_of_way_branch/;
    }

    # create "creation parent"
    my $dir_parent = path('git-02-parent');
    $dir_parent->remove_tree({ safe => 0 });
    system qw/git clone/, $dir_master->child('.git'), $dir_parent;
    $dir_parent->child('parent-file')->spew("Parent file contents\n");

    {
        local $CWD = $dir_parent;
        system qw/git checkout master/;
        system qw/git add ./;
        system qw/git commit -m /, 'First of parents commits';
        system qw/git push/;
    }

    # create "creation child"
    my $dir_child = path('git-03-child');
    $dir_child->remove_tree({ safe => 0 });
    system qw/git clone/, $dir_master->child('.git'), $dir_child;
    $dir_child->child('child-file')->spew("Child file contents\n");

    {
        local $CWD = $dir_child;
        system qw/git checkout master/;
        system qw/git add ./;
        system qw/git commit -m /, 'First of child commits';
        system qw/git push/;
    }

    return;
}

__DATA__

=head1 NAME

runner - <One-line description of commands purpose>

=head1 VERSION

This documentation refers to runner version 1.1.20

=head1 SYNOPSIS

   runner [option]

 OPTIONS:
  -o --other         other option

  -v --verbose       Show more detailed option
     --version       Prints the version information
     --help          Prints this help information
     --man           Prints the full documentation for runner



=head1 DESCRIPTION

A full description of the module and its features.

May include numerous subsections (i.e., =head2, =head3, etc.).


=head1 SUBROUTINES/METHODS

A separate section listing the public components of the module's interface.

These normally consist of either subroutines that may be exported, or methods
that may be called on objects belonging to the classes that the module
provides.

Name the section accordingly.

In an object-oriented module, this section should begin with a sentence (of the
form "An object of this class represents ...") to give the reader a high-level
context to help them understand the methods that are subsequently described.

=head1 DIAGNOSTICS

A list of every error and warning message that the module can generate (even
the ones that will "never happen"), with a full explanation of each problem,
one or more likely causes, and any suggested remedies.

=head1 CONFIGURATION AND ENVIRONMENT

A full explanation of any configuration system(s) used by the module, including
the names and locations of any configuration files, and the meaning of any
environment variables or properties that can be set. These descriptions must
also include details of any configuration language used.

=head1 DEPENDENCIES

A list of all of the other modules that this module relies upon, including any
restrictions on versions, and an indication of whether these required modules
are part of the standard Perl distribution, part of the module's distribution,
or must be installed separately.

=head1 INCOMPATIBILITIES

A list of any modules that this module cannot be used in conjunction with.
This may be due to name conflicts in the interface, or competition for system
or program resources, or due to internal limitations of Perl (for example, many
modules that use source code filters are mutually incompatible).

=head1 BUGS AND LIMITATIONS

A list of known problems with the module, together with some indication of
whether they are likely to be fixed in an upcoming release.

Also, a list of restrictions on the features the module does provide: data types
that cannot be handled, performance issues and the circumstances in which they
may arise, practical limitations on the size of data sets, special cases that
are not (yet) handled, etc.

The initial template usually just has:

There are no known bugs in this module.

Please report problems to Ivan Wills (ivan.wills@gmail.com).

Patches are welcome.

=head1 AUTHOR

Ivan Wills - (ivan.wills@gmail.com)

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2014 Ivan Wills (14 Mullion Close, Hornsby Heights, NSW Australia 2077).
All rights reserved.

This module is free software; you can redistribute it and/or modify it under
the same terms as Perl itself. See L<perlartistic>.  This program is
distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

=cut
